version: "3.1"

services:

  chat:
    container_name: chat
    image: chat
    restart: always
    depends_on:
      - redis
    ports:
      - "8000:8000"
    networks:
      bot_net:
        ipv4_address: 10.10.1.1

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "5002:6379"
    networks:
      bot_net:
        ipv4_address: 10.10.1.2
    volumes:
      - ./data/redis:/data

networks:
  bot_net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.1.0/16
